'use client'
import type { ContextCard } from '@/types'

interface Props {
  card: ContextCard
  isGenerating?: boolean
  onShowWaiting?: () => void
  onRemindLater?: () => void
  onDismiss: () => void
}

const CARD_STYLES: Record<string, string> = {
  open:    'bg-gradient-to-br from-sage-50 to-sage-100 border-sage-200',
  reentry: 'bg-gradient-to-br from-terracotta-50 to-cream-100 border-terracotta-200',
}

const CARD_LABELS: Record<string, { icon: string; label: string }> = {
  open:    { icon: '🌿', label: 'Your day so far' },
  reentry: { icon: '👋', label: 'Welcome back' },
}

export default function ContextCardDisplay({ card, isGenerating, onShowWaiting, onRemindLater, onDismiss }: Props) {
  const style = CARD_STYLES[card.type] ?? CARD_STYLES.open
  const meta  = CARD_LABELS[card.type] ?? CARD_LABELS.open
  const footerLabel = card.generated_by === 'ai' ? 'Generated by AI' : 'Saved by Context'

  return (
    <div className={`rounded-card border-2 p-5 animate-fade-up ${style} ${isGenerating ? 'animate-pulse-soft' : ''}`}>
      {/* Label row */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-1.5">
          <span className="text-base">{meta.icon}</span>
          <span className="text-xs font-medium text-warm-500 uppercase tracking-wide">{meta.label}</span>
          {card.type === 'reentry' && (
            <span className="ml-1 px-2 py-0.5 rounded-pill bg-terracotta-100 text-terracotta-600 text-xs font-medium">
              Re-entry
            </span>
          )}
        </div>
        <button
          onClick={onDismiss}
          className="w-6 h-6 rounded-full bg-warm-200/60 flex items-center justify-center
                     text-warm-500 hover:text-warm-800 hover:bg-warm-200 transition-colors text-sm leading-none"
          title="Dismiss card"
        >
          ×
        </button>
      </div>

      {/* Card title */}
      <h2 className="font-serif text-lg font-semibold text-warm-900 mb-2 leading-snug">
        {card.title}
      </h2>

      {/* Card body */}
      <p className="text-warm-700 text-sm leading-relaxed whitespace-pre-line">
        {card.body}
      </p>

      <div className="grid grid-cols-2 gap-2 mt-4">
        <button
          onClick={onShowWaiting}
          className="rounded-xl bg-warm-700 text-cream-100 py-2 text-sm font-medium active:scale-[0.98] transition-all"
        >
          Show waiting tasks
        </button>
        <button
          onClick={onRemindLater}
          className="rounded-xl border border-warm-200 text-warm-600 py-2 text-sm font-medium active:scale-[0.98] transition-all"
        >
          Remind me later
        </button>
        <button
          onClick={onDismiss}
          className="col-span-2 rounded-xl border border-warm-200 text-warm-500 py-2 text-sm font-medium active:scale-[0.98] transition-all"
        >
          Dismiss
        </button>
      </div>

      {/* Footer */}
      <p className="text-warm-300 text-xs mt-3">
        {new Date(card.created_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true })}
        {' · '}{footerLabel}
      </p>
    </div>
  )
}
